# Generated by Django 3.1.4 on 2020-12-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='Hey there ! I am using img-shr', max_length=250),
        ),
    ]
